spring:

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


  datasource:
    url: jdbc:h2:mem:library;DB_CLOSE_DELAY=-1
    initialization-mode: always
    driverClassName: org.h2.Driver

  logging:
    file:
      clean-history-on-start: true
      name: logs/info.log
   pattern:
     file:  %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger [uid=%X{UID}] - %msg%n

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    # Включает информацию о сборке (spring-boot-maven-plugin)
    build:
      enabled: true
    # Включает информацию о приложении из application.yml
    env:
      enabled: true
    # Включает информацию о git (git-commit-id-plugin)
    git:
      mode: "full"
# Собственно, сама информация
info:
  app:
    # Пример фильтрации свойств Maven
    version: @project.version@
    author: tank
    description: This my description
